version: "2.4"
services:
  #Laravel App
  app:
    build:
      context: ./app
      dockerfile: php.Dockerfile
    container_name: app-${APP_NAME}
    depends_on:
      - "db"
    tty: true
    env_file: ./app/.env
    environment:
      - PHP_EXTENSION_XDEBUG=1
    working_dir: /var/www
    volumes:
      - /var/www/vendor
      - /var/www/node_modules
      - ./app:/var/www:delegated
      - ./app/ContainersConfig/php/local.ini:/usr/local/etc/php/conf.d/local.ini
    ports:
      - "8000:8000"

  client:
    build:
      context: ./client
      dockerfile: node.Dockerfile
    container_name: client-${APP_NAME}
    depends_on:
      - "app"
    tty: true
    env_file: ./client/.env
    working_dir: /node/app
    environment:
      - HOST=0.0.0.0
    volumes:
      - /node/app/node_modules
      - ./client:/node/app:delegated
    ports:
      - "80:80"

  #MySQL Service
  db:
    image: mysql:5.7
    container_name: db-${APP_NAME}
    logging:
      driver: none
    tty: true
    ports:
      - "3360:3360"
    environment:
      MYSQL_DATABASE: "${DB_DATABASE}"
      MYSQL_USER: "${DB_USERNAME}"
      MYSQL_PASSWORD: "${DB_PASSWORD}"
      MYSQL_ROOT_PASSWORD: "${DB_PASSWORD}"
      SERVICE_TAGS: dev
      SERVICE_NAME: mysql
    volumes:
      - dbdata:/var/lib/mysql
      - ./app/ContainersConfig/mysql/my.cnf:/etc/mysql/my.cnf

  #PhpMyAdmin
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin-${APP_NAME}
    logging:
      driver: none
    depends_on:
      - "db"
    ports:
      - "8080:80"
    volumes:
      - ./app/ContainersConfig/phpmyadmin/phpmyadmin-misc.ini:/usr/local/etc/php/conf.d/phpmyadmin-misc.ini
    environment:
      MYSQL_USER: "${DB_USERNAME}"
      MYSQL_PASSWORD: "${DB_PASSWORD}"
      MYSQL_ROOT_PASSWORD: "${DB_PASSWORD}"

#Volumes
volumes:
  dbdata:
    driver: local
    name: ${APP_NAME}-volume
