FROM node:13-slim

# Update container
RUN apt-get update && \
  apt-get install --no-install-recommends -y && \
  rm -rf /var/lib/apt/lists/*

# Tiny allows to gracefully stop node process
ENV TINI_VERSION v0.18.0
ADD https://github.com/krallin/tini/releases/download/${TINI_VERSION}/tini /tini
RUN chmod +x /tini

# Set environnement to development
ENV NODE_ENV=development

# Create node directory 
WORKDIR /node

# Copy npm dependencies
COPY package*.json yarn.lock* ./

# Create app directory to contain the app and set permission for node user
RUN mkdir app && chown -R node:node .

# Change the user to be node
USER node

# Install dependencies
RUN yarn install && yarn cache clean

# Add to PATH
ENV PATH /node/node_modules/.bin/:$PATH

# Change for app directory
WORKDIR /node/app

# Copy existing local files into container, and set permission to node user
COPY --chown=node:node  . .

# For client frameworks in development
#ENV HOST 0.0.0.0

# Tiny entrypoint
ENTRYPOINT ["/tini", "--"]

CMD [ "yarn", "dev" ]

