FROM node:13 as builder

RUN apt-get update

# Create directory 
WORKDIR /home/app

# Install npm dependencies
COPY package.json package-lock.json* yarn.lock* /home/app/
RUN yarn install

# Copy existing local files into container, and set permission
COPY . /home/app

ENV HOST 0.0.0.0

CMD [ "yarn", "start" ]