FROM node:latest as builder

# Install yarn 
RUN curl -sL https://deb.nodesource.com/setup_10.x | bash - \
  && curl -sS https://dl.yarnpkg.com/debian/pubkey.gpg | apt-key add - \
  && echo "deb https://dl.yarnpkg.com/debian/ stable main" | tee /etc/apt/sources.list.d/yarn.list

RUN apt-get update \
  && apt-get install -y yarn

# Create directory 
RUN mkdir -p /home/app
WORKDIR /home/app

# Install npm dependencies
COPY package.json package-lock.json* yarn.lock* /home/app/
RUN yarn install

# Copy existing local files into container, and set permission
COPY . /home/app

ENV HOST 0.0.0.0

CMD [ "yarn", "start" ]

# FROM nginx
# EXPOSE 3000
# COPY ./nginx/default.conf /etc/nginx/conf.d/default.conf
# COPY --from=builder /home/nodejs/app/build /usr/share/nginx/html