FROM bjmrq/laravel:php-7.4-node-10

# Add user for laravel application
RUN groupadd -g 1000 www
RUN useradd -u 1000 -ms /bin/bash -g www www

# Change permission to allow www to add packages
RUN chown -R www:www .

# Change current user to www
USER www

# Set development env
ENV NODE_ENV=development

# Install npm dependencies
COPY --chown=www:www package*.json yarn.lock* /var/www/
RUN yarn install && yarn cache clean

# Add to PATH
ENV PATH /var/www/node_modules/.bin/:$PATH

# Copy existing application directory permissions
COPY --chown=www:www . /var/www

# Expose port 9000 and start php-fpm server
EXPOSE 9000

# This command will required to have previously installed Composer dependencies (using install.sh in ContainerConfig)
CMD ["php", "artisan", "serve", "--host=0.0.0.0", "--port=8000"]
